[xfer_fun]
numerator = [1.0]
denominator = [1.0, 2.0, 1.0]
time_delay = 0.0

[frequency_range]
log10_range_lim = [-4.0, 2.0]
num_points = 1000

[plotting]
fig_size = [7.5, 4.0]
xlim = [-2.0, 2.0]
xlabel = "Re(F(jω))"
ylim = [-2.0, 2.0]
ylabel = "Im(F(jω))"
pad_inches = 0.25
dpi = 300
axis_equal = true
grid = true
