[xfer_fun]
numerator = [40.0, 80.0, 40.0]
denominator = [1.0, -19.86, 98.6, 0.0]
time_delay = 0.0

[frequency_range]
log10_range_lim = [-3.5, 3.5]
num_points = 1500

[plotting]
fig_size = [7.5, 4.0]
xlim = [-2.0, 2.0]
xlabel = "Re(Fₒ(jω))"
ylim = [-2.0, 2.0]
ylabel = "Im(Fₒ(jω))"
title_string = "ω = {frequency} rad/s, Winkeländerung = {angle_change}°"
axis_equal = true
grid = true

[plotting.export]
output_dir = "/tmp/nyquist_h8_1"
frame_prefix = "frame_"
dpi = 300
pad_inches = 0.25

[plotting.response]
label = "Fₒ(jω)"
color = "#0065bd"  # tum blue

[plotting.ray]
label = "Fahrstrahl"
color = "#e37222"  # tum orange

[plotting.wedge]
radius = 0.5
alpha = 0.4
color = "#e37222"  # tum orange

[animation]
num_frames = 250
